#ifndef INC_RRALGLIB_CONFIG_H_
#define INC_RRALGLIB_CONFIG_H_

#ifdef __cplusplus
 extern "C" {
#endif

// SAMPLE RATE IN HZ // Default: 25
#define SAMPLE_RATE 64

// DATA WINDOW SIZE IN SECONDS // Default: 20
#define DATA_WINDOW 20

// THE AMOUNT OF SAMPLES TO ACCUMULATE BEFORE RERUNNING ALGORITHMS // Default: SAMPLE_RATE
#define RRAL_DELTA_SAMPLES SAMPLE_RATE

// LIBRARY FIXED POINT VALUE // Default: 16
#define FIXED_POINT 16

// ENABLE OR DISABLE CWT FUNCTIONS SO THE PROJECT CAN BE COMPILED WITHOUT dsps_fft2r.h // Default: 0
#define RRAL_CWT_ENABLED 0

// WAVELET // Default: 0 // 0 - gaus2, 1 - mexh
#define RRAL_CWT_WAVELET 0 

// CWT RESOLUTION //
#define CWT_SCALES_SIZE 5

#ifdef __cplusplus
}
#endif

#endif